channels:
  targets:
  - [nomr, main]
travis:
  secure:
    BINSTAR_TOKEN: VduTQb5GngBm6zlGVzBLhiHrYtF6QNwHgjWT0+If91rQpRE0BF8uVtLMcGYN0VDi7cddpVsD58Z0iNACYAeU6oBKGsYIbLtrD9eoxpQUL3LIwGb0dKM5NFK+3N/3gG+GN7I106D+I5FcTaBe4jR5/ZIKrAdt+AbN4f9TUUrxmJeVMU7QjeCMR+/uWKGgUAd0I5K0k3obrmFjIwDzONCF/45owHthOfq5NaZVj35kfjvmO5JWDC4QSWOUpfnQfuMs2p4VKE9NDS1yAvxF6ejBeyAS/U1LbmyLrKgddk3P8NPh3rKyhSJJ9IcOtnjxT5t6SHvJtskFHOoeVJMWgrUhEjBh4rm49ohmhUZ7LXqBQ6XislABfRd5BCQXfxo5bUKoxhGE8eUy23akYHN6rRWKajetTdqT1vJ5LKWEkOSMdCJdPYN880aetrpTrJmjS8mjCY1L30xxxSQeZoxzkTv0pFAJR8VliME8MeD3q8zPj2n0EraadCSuMI1WMmjyfv+cISNGoHKDY/TCGPcJo4Yyoc+bH7DUWVNR7J/Ek+E5a7QVA00ws6KCsA7N3+pISbfwaZpO6yTfC9M2yXf/z+lEvYS4TJNnfGUp2CbUOr/TJJksUqRCwr1VbDVU/CeYqNcnYFYBOdeCmreyeZRW0ADACyMmbc4iz+9iUNR20La/G4c=
appveyor:
  secure:
    BINSTAR_TOKEN: iCSCYlUvHy+Dj6sGoT0mpXdKB5SeNBmJm6Q9e+ylBTg4FoemSUf2MFxsN2J1Y0u2
